# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_aKXeerp14aT0z-gFYql-JON1XFSzYqe
"""

# Verification Email: 24f2000846@ds.study.iitm.ac.in

import matplotlib.pyplot as plt

# Quarterly CAC data
quarters = ['Q1', 'Q2', 'Q3', 'Q4']
cac_values = [224.21, 228.3, 231.97, 229.14]
average_cac = 228.41
industry_target = 150

# Plotting CAC trend with industry target line
plt.figure(figsize=(8, 6))
plt.plot(quarters, cac_values, marker='o', label='Quarterly CAC')
plt.axhline(y=industry_target, color='r', linestyle='--', label='Industry Target (150)')
plt.title('Customer Acquisition Cost (CAC) Trend - 2024')
plt.ylabel('CAC ($)')
plt.xlabel('Quarter')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.savefig('cac_trend.png')
plt.show()

# Employee Department Analysis
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Sample employee data - 100 rows with department and region (for demonstration, smaller subset shown)
data = {
    'EmployeeID': range(1, 101),
    'Department': ['Marketing', 'Sales', 'IT', 'HR', 'Finance', 'Marketing', 'IT', 'Sales'] * 12 + ['Marketing', 'HR', 'Finance', 'Marketing'],
    'Region': ['North', 'South', 'East', 'West'] * 25
}

df = pd.DataFrame(data)

# Calculate frequency count for the Marketing department
marketing_freq = df['Department'].value_counts().get('Marketing', 0)
print(f"Frequency count for Marketing department: {marketing_freq}")

# Plot histogram of department distribution
plt.figure(figsize=(10, 6))
sns.countplot(data=df, x='Department', palette='Set2')
plt.title('Department Distribution of Employees')
plt.xlabel('Department')
plt.ylabel('Number of Employees')
plt.xticks(rotation=45)
plt.tight_layout()

# Save plot as PNG for embedding
plt.savefig("department_histogram.png")

# Display the plot (if running interactively)
plt.show()